# Generated by Django 5.2.7 on 2025-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('App', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Type', models.CharField(max_length=20)),
                ('Required_Age', models.IntegerField(null=True)),
                ('Recommendations', models.IntegerField(null=True)),
                ('Is_Free', models.BooleanField()),
                ('Discount_Percent', models.IntegerField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Coming_Soon', models.BooleanField()),
                ('Release_Date', models.DateField(null=True)),
                ('Full_AppID', models.IntegerField(null=True)),
                ('Image_Link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('Apps', models.ManyToManyField(to='GamesApp.app')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('Developer', models.IntegerField(primary_key=True, serialize=False)),
                ('Developer_Name', models.CharField(max_length=100)),
                ('Apps', models.ManyToManyField(to='GamesApp.app')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('Genre', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('Apps', models.ManyToManyField(to='GamesApp.app')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=100)),
                ('Apps', models.ManyToManyField(to='GamesApp.app')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('Publisher', models.IntegerField(primary_key=True, serialize=False)),
                ('Publisher_Name', models.CharField(max_length=100)),
                ('Apps', models.ManyToManyField(to='GamesApp.app')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Rank', models.IntegerField()),
                ('Player_Count', models.IntegerField(null=True)),
                ('Apps', models.ManyToManyField(to='GamesApp.app')),
            ],
        ),
    ]
