# Generated by Django 5.2.7 on 2025-11-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APPS',
            fields=[
                ('AppID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('Description', models.TextField(max_length=500, null=True)),
                ('Type', models.CharField(max_length=20)),
                ('Required_Age', models.IntegerField(null=True)),
                ('Recommendations', models.IntegerField(null=True)),
                ('Is_Free', models.BooleanField()),
                ('Discount_Percent', models.IntegerField(null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('Coming_Soon', models.BooleanField()),
                ('Release_Date', models.DateField(null=True)),
                ('Full_AppID', models.IntegerField(null=True)),
                ('Image_Link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CATEGORIES',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DEVELOPERS',
            fields=[
                ('DeveloperID', models.IntegerField(primary_key=True, serialize=False)),
                ('Developer_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GENRES',
            fields=[
                ('GenreID', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LANGUAGES',
            fields=[
                ('LanguageID', models.IntegerField(primary_key=True, serialize=False)),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PUBLISHERS',
            fields=[
                ('PublisherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Publisher_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APP_CATEGORIES',
            fields=[
                ('pk', models.CompositePrimaryKey('AppID', 'CategoryID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.apps')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='APP_DEVELOPERS',
            fields=[
                ('pk', models.CompositePrimaryKey('AppID', 'DeveloperID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.apps')),
                ('DeveloperID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.developers')),
            ],
        ),
        migrations.CreateModel(
            name='APP_GENRES',
            fields=[
                ('pk', models.CompositePrimaryKey('AppID', 'GenreID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.apps')),
                ('GenreID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.genres')),
            ],
        ),
        migrations.CreateModel(
            name='APP_LANGUAGES',
            fields=[
                ('pk', models.CompositePrimaryKey('AppID', 'LanguageID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Audio_Support', models.BooleanField()),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.apps')),
                ('LanguageID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.languages')),
            ],
        ),
        migrations.CreateModel(
            name='APP_PUBLISHERS',
            fields=[
                ('pk', models.CompositePrimaryKey('AppID', 'PublisherID', blank=True, editable=False, primary_key=True, serialize=False)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.apps')),
                ('PublisherID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.publishers')),
            ],
        ),
        migrations.CreateModel(
            name='RANKINGS',
            fields=[
                ('pk', models.CompositePrimaryKey('AppID', 'Date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Rank', models.IntegerField()),
                ('Player_Count', models.IntegerField(null=True)),
                ('AppID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GamesApp.apps')),
            ],
        ),
    ]
