# Generated by Django 5.2.7 on 2025-11-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='Apps',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='Apps',
        ),
        migrations.RemoveField(
            model_name='language',
            name='Apps',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='Apps',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
