# Generated by Django 5.2.7 on 2025-11-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0002_remove_developer_apps_remove_genre_apps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='Apps',
        ),
        migrations.AddField(
            model_name='ranking',
            name='App',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GamesApp.app'),
            preserve_default=False,
        ),
    ]
