# Generated by Django 5.2.7 on 2025-11-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0003_remove_ranking_apps_ranking_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='App',
            new_name='AppID',
        ),
    ]
