# Generated by Django 5.2.7 on 2025-11-14 20:18
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0004_rename_app_app_appid'),
    ]

    operations = [
        TrigramExtension(),
    ]
