# Generated by Django 5.2.7 on 2026-02-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamesApp', '0005_auto_20251114_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='Categories',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='Developers',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='Genres',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='Languages',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='Publishers',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
